const COLLECTION_DATA = {
  lifedeathloveart: {
    name: 'Life, Death, Love and Art',
    nombre: 'La Vida, La Muerte, El Amor y El Arte',
    size: 'square',
    imagePATH: require('../../assets/life-death-love-art.jpg'),
    price: 40,
    routeName: 'lifedeathloveart',
    description: 'This work is a painting based on the lives and complicated relationship — including their two marriages — of Mexican artists Frida Kahlo and Diego Rivera. Despite a large age gap, Frida died years before the older Diego after a lifetime of physical suffering caused by an accident as an early teenager. The two created a fascinating story together and contributed some of the most beautiful and deeply significant works of art of the twentieth century. Shortly before Rivera died he said that his entire life had been Frida Kahlo.',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Oil on Canvas',
    medio: 'Óleo sobre lienzo',
    dimensions: '36 in. x 36 in. (91.5 cm x 91.5 cm)',
    id: 1
  },
  blackbox: {
    name: 'Black Box',
    nombre: 'La Caja Negra',
    imagePATH: require('../../assets/black-box.jpg'),
    price: 30,
    routeName: 'blackbox',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Acrylic on Wood Panels',
    medio: 'Acrílico sobre paneles de madera',
    dimensions: '17 in. x 22 in. (43.2 cm x 55.9 cm)',
    id: 2
  },
  squarescircles: {
    name: 'Squares and Circles',
    nombre: 'Cuadros y Circulos',
    imagePATH: require('../../assets/squares-circles.jpg'),
    price: 0,
    routeName: 'squarescircles',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Acrylic on Canvas',
    medio: 'Acrílico sobre lienzo',
    dimensions: '48 in. x 60 in. (123 cm x 152.5 cm)',
    id: 3
  },
  picassovermeer4: {
    name: 'Picasso in a Vermeer 4',
    nombre: 'Picasso en un Vermeer 1',
    imagePATH: require('../../assets/picasso-vermeer-4.jpg'),
    price: 35,
    routeName: 'picassovermeer4',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Graphite on Paper',
    medio: 'Grafito sobre papel',
    dimensions: '12 in. x 14 in. (30.5 cm x 35.5 cm)',
    id: 4
  },
  nogales: {
    horizontal: 'long',
    name: 'Nogales',
    nombre: 'Nogales',
    imagePATH: require('../../assets/nogales-mural.jpg'),
    price: 180,
    routeName: 'nogales',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Oil on Canvas',
    medio: 'Óleo sobre lienzo',
    dimensions: '26 in. x 56 in. (66 cm x 142.2 cm)',
    id: 5
  },
  fridakahlo: {
    name: 'Frida Kahlo',
    nombre: 'Frida Kahlo',
    imagePATH: require('../../assets/frida-kahlo.jpg'),
    price: 35,
    routeName: 'fridakahlo',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Oil on Canvas',
    medio: 'Óleo sobre lienzo',
    dimensions: '18 in. x 22 in. (45.7 cm x 55.9 cm)',
    id: 6
  },
  clara: {
    name: 'Clara',
    nombre: 'Clara',
    imagePATH: require('../../assets/clara.jpg'),
    price: 0,
    routeName: 'clara',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Oil on Masonite Board',
    medio: 'Óleo sobre tablero de masonita',
    dimensions: '12 in. x 14 in. (30.5 cm x 35.5 cm)',
    id: 7
  },
  fatman: {
    name: 'Fat Man',
    nombre: 'Fat Man',
    imagePATH: require('../../assets/fat-man.jpg'),
    price: 0,
    routeName: 'fatman',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Acrylic on Sculpted Wood',
    medio: 'Acrílico sobre madera esculpida',
    dimensions: '24 in. x 15.8 in. (61 cm x 40.1 cm) -- circumference x height',
    id: 8
  },
  carloscrayons: {
    name: 'Carlos and Crayons',
    nombre: 'Carlos and Crayolas',
    imagePATH: require('../../assets/carlos-and-crayons.jpg'),
    price: 0,
    routeName: 'carloscrayons',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Oil on Canvas',
    medio: 'Óleo sobre lienzo',
    dimensions: '48 in. x 60 in. (123 cm x 152.5 cm)',
    id: 9
  },
  vangogh: {
    name: 'Van Gogh',
    nombre: 'Van Gogh',
    imagePATH: require('../../assets/vangogh-3.jpg'),
    price: 25,
    routeName: 'vangogh',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Graphite on Paper',
    medio: 'Grafito sobre papel',
    dimensions: '12.5 in. x 13.5 in. (31.8 cm x 34.3 cm)',
    id: 10
  },
  picassovermeer2: {
    name: 'Picasso in a Vermeer 2',
    nombre: 'Picasso en un Vermeer 2',
    imagePATH: require('../../assets/picasso-vermeer-2.jpg'),
    price: 25,
    routeName: 'picassovermeer2',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Oil on Canvas',
    medio: 'Óleo sobre lienzo',
    dimensions: '12 in. x 16 in. (30.5 cm x 40.6 cm)',
    id: 11
  },
  beethoven: {
    name: 'Beethoven',
    nombre: 'Beethoven',
    imagePATH: require('../../assets/beethoven.jpg'),
    price: 85,
    routeName: 'beethoven',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Oil on Canvas',
    medio: 'Óleo sobre lienzo',
    dimensions: '60 in. x 84 in. (152.4 cm x 213.4 cm)',
    id: 12
  },
  jean: {
    name: 'Jean',
    nombre: 'Jean',
    imagePATH: require('../../assets/jean.jpg'),
    price: 0,
    routeName: 'jean',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Oil on Canvas',
    medio: 'Óleo sobre lienzo',
    dimensions: '30 in. x 34 in. (76.2 cm x 86.4 cm)',
    id: 13
  },
  picassovermeer1: {
    name: 'Picasso in a Vermeer 1',
    nombre: 'Picasso en un Vermeer 1',
    imagePATH: require('../../assets/picasso-vermeer-1.jpg'),
    price: 40,
    routeName: 'picassovermeer1',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Acrylic on Canvas',
    medio: 'Acrílico sobre lienzo',
    dimensions: '16 in. x 18 in. (40.6 cm x 45.7 cm)',
    id: 14
  },
  normajean: {
    name: 'Norma Jean (Marylin)',
    nombre: 'Norma Jean (Marylin)',
    imagePATH: require('../../assets/norma-jean.jpg'),
    price: 30,
    routeName: 'normajean',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Acrylic on Canvas',
    medio: 'Acrílico sobre lienzo',
    dimensions: '32 in. x 32 in. (81.3 cm x 81.3 cm)',
    id: 15
  },
  mercadodiaz: {
    name: 'Mercado Díaz',
    nombre: 'Mercado Díaz',
    imagePATH: require('../../assets/mercado.jpg'),
    price: 0,
    routeName: 'mercadodiaz',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Oil on Canvas',
    medio: 'Óleo sobre lienzo',
    dimensions: '16 in. x 20 in. (40.6 cm x 50.8 cm)',
    id: 16
  },
  picassovermeer3: {
    name: 'Picasso in a Vermeer 3',
    nombre: 'Picasso en un Vermeer 3',
    imagePATH: require('../../assets/picasso-vermeer-3.jpg'),
    price: 40,
    routeName: 'picassovermeer3',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Oil on Canvas',
    medio: 'Óleo sobre lienzo',
    dimensions: '19 in. x 22 in. (48.3 cm x 55.9 cm)',
    id: 17
  },
  america: {
    name: 'America',
    nombre: 'America',
    imagePATH: require('../../assets/mother-child.jpg'),
    price: 35,
    routeName: 'america',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    descripcion: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos nemo nesciunt reiciendis quis debitis? Tempore laboriosam, reiciendis dolorem laudantium ea ullam temporibus nesciunt aliquam dolorum assumenda corrupti illo saepe dolores nostrum asperiores tenetur neque repellat, minima consequatur? Cupiditate dolores quia dolore laboriosam aliquid consequatur eos assumenda earum amet soluta placeat, nihil ab dolor tempora possimus, perspiciatis vero veniam architecto? Blanditiis non, quis libero autem nemo sit nam quia voluptatum accusamus?',
    medium: 'Oil on Canvas',
    medio: 'Óleo sobre lienzo',
    dimensions: '22 in. x 26 in. (55.9 cm x 66 cm)',
    id: 18
  }
}

export default COLLECTION_DATA;
// export to collection.reducer